### ISSUE TITLE
similar position of Z for shape and time vector

### ISSUE THREAD

**Issue by inspirit** [vincent-leguen/STRIPE#2]
https://github.com/vincent-leguen/STRIPE/blob/fd63eff2a277fe871968b6182a0cea61fc4089de/trainer/trainer.py#L217

I noticed that you have sampled z code at the same position when sending to decoder during train of shape and time stripe model.

however in evaluation code you place z at the beginning or end of vector depending on what type of stripe (shape/time) we are working with.

would you be so kind to explain correct way building code-vector for decoder?
thank you.

**Comment by vincent-leguen** [comment]
Hi @inspirit , thank you, it is of course (z,z_f) for stripe shape and (z_f,z) for stripe_time since in our convention we concatenate (zs,zt) in that order. I have made the update in Github.
Best
Vincent
